POST http://localhost:3000/api/teachers
Content-Type: application/json

{
        "firstName" : "Abdul-Latif",
        "lastName" : "Mohammed",
        "email" : "latifm8360@gmail.com"
}

###
http://localhost:3000/api/students

###
http://localhost:3000/api/classes

###
http://localhost:3000/api/classes/sections

###
POST http://localhost:3000/api/classes
Content-Type: application/json

{
     "className" : "Primary 3"
}

###
http://localhost:3000/api/classes/classandsections

###
http://localhost:3000/api/teachers

###
PUT http://localhost:3000/api/classes/assignTeacher
Content-Type: application/json

{
     "classSectionId" : "cm7krbcfe00028uq3t9fnv9d6",
     "teacherId" : "cm7tb2iw2000411genl7mwtw5"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
        "email" : "admin@gmail.com",
        "password" :"ronsard@123",
        "role" : "admin"
}
